# Generated by Django 2.0 on 2020-04-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('moisture', models.FloatField()),
                ('lux', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatureSensor', models.FloatField()),
                ('moistureSensor', models.FloatField()),
                ('luxSensor', models.FloatField()),
            ],
        ),
    ]
