# Generated by Django 2.0 on 2020-04-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miHuertaSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('moisture', models.FloatField()),
                ('lux', models.FloatField()),
                ('isSelected', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
        migrations.DeleteModel(
            name='Plants',
        ),
    ]
